import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { faStar } from "@fortawesome/free-solid-svg-icons";
import { LineChart } from "@/components/chart/line";
import { MainHeader } from "@/components/main/header";
import { Breads } from "@/components/main/breads";
import { MainFooter } from "@/components/main/footer";
const Home: NextPage = () => {
  let breadCrumbs = [
    {
      name: "Token details",
      href: "/markets",
    },
    {
      name: "BNB",
      href: "/info/bnb",
    },
  ];

  const data: Array<number> = [];
  let prev = 100;
  for (let i = 0; i < 500; i++) {
    prev += 5 - Math.random() * 10;
    data.push(Math.round(prev));
  }
  const coinDetail = {
    name: "Binance Coin",
    symbol: "BNB",
    image: "/assets/icons/ic-BinanceCoin.png",
    tags: ["BSC", "Platform", "POS", "Coin", "Margin"],
    priceHistory: data.map((x, index) => {
      return {
        date: addDays(new Date(), index).toLocaleDateString("en-US"),
        price: data[index],
      };
    }),
    chartPeriod: [
      {
        name: "24H",
        value: "24H",
      },
      {
        name: "7D",
        value: "7D",
      },
      {
        name: "1M",
        value: "1M",
      },
      {
        name: "3M",
        value: "3M",
      },
      {
        name: "6M",
        value: "6M",
      },
      {
        name: "1Y",
        value: "1Y",
      },
      {
        name: "All",
        value: "All",
      },
    ],
    priceChange: [
      {
        percent: 4.67,
        period: "24H",
      },
      {
        percent: 10.14,
        period: "Last 7 days",
      },

      {
        percent: 15.9,
        period: "30 days",
      },

      {
        percent: -22.84,
        period: "90 days",
      },

      {
        percent: 30.5,
        period: "180 days",
      },

      {
        percent: 61.41,
        period: "365 days",
      },

      {
        percent: 1861.07,
        period: "all",
      },
    ],
  };
  function addDays(date: Date, days: number) {
    var result = new Date(date);
    result.setDate(result.getDate() + days);
    return result;
  }

  return (
    <div className="bg-gradient-to-b from-[#f4f6f7] to-[#fbfbfb] ">
      <Head>
        <title>CoinEx - The Global Cryptocurrency Exchange</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          data-hid="g_viewport"
          content="width=1280"
        />
      </Head>
      <MainHeader />

      <main className="xl:w-[1280px] mx-auto ">
        <Breads breadCrumbs={breadCrumbs} />

        <div className="top-row mt-4"></div>
        <div className="top-left-box">
          <div className=" flex">
            <Image width="56px" height="56px" src={coinDetail.image}></Image>
            <div className="ms-4 leading-3">
              <div className=" flex items-center">
                <span className="text-3xl">{coinDetail.symbol}</span>
                <div className="bg-white flex items-center justify-center w-7 h-7 rounded-md border-gray-400 border ms-3">
                  <FontAwesomeIcon icon={faStar} color="grey" width="20" />
                </div>
                <div className="bg-[#ffedce] text-[#eb9d09] p-2 ms-3">
                  <span>No.4</span>
                </div>
              </div>
              <h1>{coinDetail.name}</h1>
            </div>
          </div>
          <div className="tags w-full flex mt-5">
            {coinDetail.tags.map((tag, index) => (
              <div
                key={index + "tags"}
                className="border rounded h-max w-max px-2 mx-1 text-sm text-gray-500"
              >
                <span>{tag}</span>
              </div>
            ))}
          </div>
        </div>
        <div className="chart flex justify-between w-full bg-white rounded-2xl p-3 mt-8">
          <div className="w-9/12 shrink-0">
            <h2 className="mb-4">Price</h2>
            <div className="periods flex">
              {coinDetail.chartPeriod.map((period, index) => (
                <div
                  key={index + "chartPeriod"}
                  className="border rounded h-max w-12 text-center px-2 mx-1 first:ms-0 text-sm text-gray-500"
                >
                  <button>{period.name}</button>
                </div>
              ))}
            </div>
            <div className="">
              <LineChart priceHistory={coinDetail.priceHistory} />
            </div>
          </div>
          <div className="chartSideBar w-2/12  ">
            <h2 className="mb-4">BNB price change</h2>
            <div className="flex flex-col justify-between rounded-lg border h-5/6">
              {coinDetail.priceChange.map((change, index) => (
                <div
                  key={index + "priceChange"}
                  className="flex flex-col justify-center border-b last:border-none w-full text-center h-[14.28%]   first:ms-0 text-sm text-gray-500"
                >
                  <div className="flex justify-between px-2">
                    <span>{change.period}</span>
                    <button
                      className={
                        (change.percent < 0
                          ? "text-red-500"
                          : "text-green-500") + " font-bold"
                      }
                    >
                      {change.percent + "%"}
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
        <div className="market h-[300px] bg-white rounded-2xl p-7 mt-3">
          <h2 className="mb-4">Markets</h2>
        </div>
        <div className="market h-[300px] bg-white rounded-2xl p-7 mt-3">
          <h2 className="mb-4">Coin introduction</h2>
        </div>
      </main>

      <MainFooter />
    </div>
  );
};

export default Home;
